language: node_js

sudo: false

env:
  - CXX=g++-4.8

node_js:
  - "6"
  - "5"

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - gcc-4.8

after_script: NODE_ENV=test lab --coverage-exclude views -r lcov | ./node_modules/.bin/coveralls
